sudo: required
before_install:
 - echo "deb http://www.rabbitmq.com/debian/ testing main"  | sudo tee  /etc/apt/sources.list.d/rabbitmq.list > /dev/null
 - sudo wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
 - sudo apt-key add rabbitmq-signing-key-public.asc
 - sudo apt-get update
 - sudo apt-get install rabbitmq-server -y
 - sudo service rabbitmq-server start
 - sudo rabbitmq-plugins enable rabbitmq_management
 - sudo service rabbitmq-server restart
language: node_js
node_js:
  - 0.10
  - 0.12
  - 4.0
